# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  cs488_framework_config = debug
  imgui_config = debug
  lodepng_config = debug
endif
ifeq ($(config),release)
  cs488_framework_config = release
  imgui_config = release
  lodepng_config = release
endif

PROJECTS := cs488-framework imgui lodepng

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

cs488-framework:
ifneq (,$(cs488_framework_config))
	@echo "==== Building cs488-framework ($(cs488_framework_config)) ===="
	@${MAKE} --no-print-directory -C build -f cs488-framework.make config=$(cs488_framework_config)
endif

imgui:
ifneq (,$(imgui_config))
	@echo "==== Building imgui ($(imgui_config)) ===="
	@${MAKE} --no-print-directory -C build -f imgui.make config=$(imgui_config)
endif

lodepng:
ifneq (,$(lodepng_config))
	@echo "==== Building lodepng ($(lodepng_config)) ===="
	@${MAKE} --no-print-directory -C build -f lodepng.make config=$(lodepng_config)
endif

clean:
	@${MAKE} --no-print-directory -C build -f cs488-framework.make clean
	@${MAKE} --no-print-directory -C build -f imgui.make clean
	@${MAKE} --no-print-directory -C build -f lodepng.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   cs488-framework"
	@echo "   imgui"
	@echo "   lodepng"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"